// Mocks generated by Mockito 5.4.6 from annotations
// in nuntium/test/features/home/data/repository/news_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nuntium/core/entities/article.dart' as _i4;
import 'package:nuntium/core/errors/crash_reporter.dart' as _i6;
import 'package:nuntium/core/network/network_info.dart' as _i5;
import 'package:nuntium/features/home/data/data_source/news_remote_data_source.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NewsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsRemoteDataSource extends _i1.Mock
    implements _i2.NewsRemoteDataSource {
  MockNewsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Article>> fetchTopHeadlines({
    required String? category,
    int? page = 1,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTopHeadlines, [], {
              #category: category,
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i3.Future<List<_i4.Article>>.value(<_i4.Article>[]),
          )
          as _i3.Future<List<_i4.Article>>);

  @override
  _i3.Future<List<_i4.Article>> searchNews({
    required String? query,
    int? page = 1,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchNews, [], {
              #query: query,
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i3.Future<List<_i4.Article>>.value(<_i4.Article>[]),
          )
          as _i3.Future<List<_i4.Article>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [CrashReporter].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrashReporter extends _i1.Mock implements _i6.CrashReporter {
  MockCrashReporter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> reportError({
    required dynamic exception,
    required StackTrace? stackTrace,
    dynamic reason,
    bool? fatal = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportError, [], {
              #exception: exception,
              #stackTrace: stackTrace,
              #reason: reason,
              #fatal: fatal,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
