// Mocks generated by Mockito 5.4.6 from annotations
// in nuntium/test/features/home/presentation/bloc/home_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nuntium/core/entities/article.dart' as _i7;
import 'package:nuntium/core/errors/failures.dart' as _i6;
import 'package:nuntium/features/bookmarks/domain/entity/bookmark_event.dart'
    as _i13;
import 'package:nuntium/features/bookmarks/domain/use_cases/check_if_saved_use_case.dart'
    as _i14;
import 'package:nuntium/features/bookmarks/domain/use_cases/toggle_bookmark_use_case.dart'
    as _i9;
import 'package:nuntium/features/bookmarks/domain/use_cases/watch_bookmarks_changes_use_case.dart'
    as _i12;
import 'package:nuntium/features/categories/domain/entities/category_entity.dart'
    as _i11;
import 'package:nuntium/features/categories/domain/repository/cateogries_repository.dart'
    as _i3;
import 'package:nuntium/features/categories/domain/use_case/get_cateogories_use_case.dart'
    as _i10;
import 'package:nuntium/features/home/domain/use_cases/fetch_news_use_case.dart'
    as _i4;
import 'package:nuntium/features/home/domain/use_cases/search_news_use_case.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoriesRepository_1 extends _i1.SmartFake
    implements _i3.CategoriesRepository {
  _FakeCategoriesRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FetchNewsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchNewsUseCase extends _i1.Mock implements _i4.FetchNewsUseCase {
  MockFetchNewsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.Article>>> call({
    required String? category,
    required int? page,
    required int? pageSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #category: category,
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.Article>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.Article>>(
                    this,
                    Invocation.method(#call, [], {
                      #category: category,
                      #page: page,
                      #pageSize: pageSize,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.Article>>>);
}

/// A class which mocks [SearchNewsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchNewsUseCase extends _i1.Mock implements _i8.SearchNewsUseCase {
  MockSearchNewsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.Article>>> call({
    required String? query,
    required int? page,
    required int? pageSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #query: query,
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.Article>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.Article>>(
                    this,
                    Invocation.method(#call, [], {
                      #query: query,
                      #page: page,
                      #pageSize: pageSize,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.Article>>>);
}

/// A class which mocks [ToggleBookmarkUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleBookmarkUseCase extends _i1.Mock
    implements _i9.ToggleBookmarkUseCase {
  MockToggleBookmarkUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> call({required _i7.Article? article}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#article: article}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [GetCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategoriesUseCase extends _i1.Mock
    implements _i10.GetCategoriesUseCase {
  MockGetCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CategoriesRepository get categoriesRepository =>
      (super.noSuchMethod(
            Invocation.getter(#categoriesRepository),
            returnValue: _FakeCategoriesRepository_1(
              this,
              Invocation.getter(#categoriesRepository),
            ),
          )
          as _i3.CategoriesRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i11.CategoryEntity>>> call({
    bool? isForHome = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#isForHome: isForHome}),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.Failure, List<_i11.CategoryEntity>>
                >.value(
                  _FakeEither_0<_i6.Failure, List<_i11.CategoryEntity>>(
                    this,
                    Invocation.method(#call, [], {#isForHome: isForHome}),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i11.CategoryEntity>>>);
}

/// A class which mocks [WatchBookmarksChangesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchBookmarksChangesUseCase extends _i1.Mock
    implements _i12.WatchBookmarksChangesUseCase {
  MockWatchBookmarksChangesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i13.BookmarkChangeEvent> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Stream<_i13.BookmarkChangeEvent>.empty(),
          )
          as _i5.Stream<_i13.BookmarkChangeEvent>);
}

/// A class which mocks [CheckIfSavedUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckIfSavedUseCase extends _i1.Mock
    implements _i14.CheckIfSavedUseCase {
  MockCheckIfSavedUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool call(String? id) =>
      (super.noSuchMethod(Invocation.method(#call, [id]), returnValue: false)
          as bool);
}
