// Mocks generated by Mockito 5.4.6 from annotations
// in nuntium/test/features/bookmarks/data/repository/bookmark_repository_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nuntium/core/models/article_hive_model.dart' as _i4;
import 'package:nuntium/core/services/storage_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i2.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveBookmark(_i4.ArticleHiveModel? bookmark) =>
      (super.noSuchMethod(
            Invocation.method(#saveBookmark, [bookmark]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  List<_i4.ArticleHiveModel> getAllBookmarks() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBookmarks, []),
            returnValue: <_i4.ArticleHiveModel>[],
          )
          as List<_i4.ArticleHiveModel>);

  @override
  _i3.Future<void> deleteBookmark(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBookmark, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  bool isArticleSaved(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#isArticleSaved, [id]),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<void> clearAllBookmarks() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllBookmarks, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
