// Mocks generated by Mockito 5.4.6 from annotations
// in nuntium/test/features/bookmarks/presentation/cubit/bookmarks_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nuntium/core/entities/article.dart' as _i3;
import 'package:nuntium/features/bookmarks/domain/entity/bookmark_event.dart'
    as _i7;
import 'package:nuntium/features/bookmarks/domain/use_cases/delete_bookmark_use_case.dart'
    as _i4;
import 'package:nuntium/features/bookmarks/domain/use_cases/get_saved_articles_use_case.dart'
    as _i2;
import 'package:nuntium/features/bookmarks/domain/use_cases/watch_bookmarks_changes_use_case.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetSavedArticlesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSavedArticlesUseCase extends _i1.Mock
    implements _i2.GetSavedArticlesUseCase {
  MockGetSavedArticlesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Article> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: <_i3.Article>[],
          )
          as List<_i3.Article>);
}

/// A class which mocks [DeleteBookmarkUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteBookmarkUseCase extends _i1.Mock
    implements _i4.DeleteBookmarkUseCase {
  MockDeleteBookmarkUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call(_i3.Article? article) =>
      (super.noSuchMethod(
            Invocation.method(#call, [article]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [WatchBookmarksChangesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchBookmarksChangesUseCase extends _i1.Mock
    implements _i6.WatchBookmarksChangesUseCase {
  MockWatchBookmarksChangesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i7.BookmarkChangeEvent> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Stream<_i7.BookmarkChangeEvent>.empty(),
          )
          as _i5.Stream<_i7.BookmarkChangeEvent>);
}
